### ISSUE TITLE
Ratify results:  2/7

### ISSUE THREAD

**Issue by bwalsh** [bmeg/bmeg-etl#81]
@prismofeverything @kellrott @buchanae @adamstruck 

# Progress  
## protobuf validation for first 10 in each file works!
```
$ DATA_DIR=/tmp/SWIFT  SAMPLE_SIZE=10 pytest tests/test_biostream.py
============================================================================================================================ test session starts =============================================================================================================================
platform darwin -- Python 2.7.13, pytest-3.0.6, py-1.4.34, pluggy-0.4.0
rootdir: /Users/walsbr/ratify, inifile:
plugins: flask-0.8.1, catchlog-1.2.2
collected 7 items

tests/test_biostream.py .......

========================================================================================================================== 7 passed in 9.25 seconds ==========================================================================================================================

```

# Needs attention
## test_ccle
* gids have blanks - protograph/ccle/ccle.Biosample.Vertex.json

## test_tcga 
 * swift IO error protograph/tcga/TCGA-LUAD/tcga.TCGA-LUAD.GeneExpression.Edge.json
 * json parse protograph/tcga/TCGA-LUAD/tcga.TCGA-LUAD.CNASegment.Vertex.json

## test_ensembl
  *  swift IO error protograph/ensembl/ensembl.Gene.Vertex.json

```
$ DATA_DIR=/tmp/SWIFT  SAMPLE_SIZE=1 pytest tests/test_protograph.py
============================================================================================================================ test session starts =============================================================================================================================
platform darwin -- Python 2.7.13, pytest-3.0.6, py-1.4.34, pluggy-0.4.0
rootdir: /Users/walsbr/ratify, inifile:
plugins: flask-0.8.1, catchlog-1.2.2
collected 9 items

tests/test_protograph.py .F...F..F

================================================================================================================================== FAILURES ==================================================================================================================================
_________________________________________________________________________________________________________________________________ test_ccle __________________________________________________________________________________________________________________________________

protograph = AttrDict({'Cohort': AttrDict({'vertexes': [{'filter': ['hasMember'], 'merge': ...label': 'hasDisease', 'to': 'term:{{disease.term}}'}], 'label': 'Biosample'})})

    def test_ccle(protograph):
        """ assert ccle data is ok """
        project_error_count = _validate_project(protograph, 'ccle')
>       assert project_error_count == 0
E       assert 1 == 0

tests/test_protograph.py:181: AssertionError
----------------------------------------------------------------------------------------------------------------------------- Captured log call ------------------------------------------------------------------------------------------------------------------------------
__init__.py                 54 DEBUG    loading paths from /tmp/SWIFT/biostream/protograph/ccle
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/ccle/ccle.Biosample.Edge.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/ccle/ccle.Biosample.Vertex.json
__init__.py                 45 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/ccle/ccle.Biosample.Vertex.json", "error_type": "AssertionError", "error": "gid contains blanks 'biosample::1321N1_CENTRAL_NERVOUS_SYSTEM' in /tmp/SWIFT/biostream/protograph/ccle/ccle.Biosample.Vertex.json\nassert False\n +  where False = _exists('')"}
__init__.py                 46 ERROR    gid contains blanks 'biosample::1321N1_CENTRAL_NERVOUS_SYSTEM' in /tmp/SWIFT/biostream/protograph/ccle/ccle.Biosample.Vertex.json
assert False
 +  where False = _exists('')
Traceback (most recent call last):
  File "/Users/walsbr/ratify/tests/__init__.py", line 33, in _logging
    yield
  File "/Users/walsbr/ratify/tests/test_protograph.py", line 135, in _validate_vertex_file
    assert _exists(gid_part), "gid contains blanks '{}' in {}".format(vertex.gid, path)  # noqa
AssertionError: gid contains blanks 'biosample::1321N1_CENTRAL_NERVOUS_SYSTEM' in /tmp/SWIFT/biostream/protograph/ccle/ccle.Biosample.Vertex.json
assert False
 +  where False = _exists('')
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/ccle/ccle.CallSet.Edge.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/ccle/ccle.CallSet.Vertex.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/ccle/ccle.ResponseCurve.Edge.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/ccle/ccle.ResponseCurve.Vertex.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/ccle/ccle.Variant.Edge.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/ccle/ccle.Variant.Vertex.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/ccle/ccle.VariantAnnotation.Edge.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/ccle/ccle.VariantAnnotation.Vertex.json
test_protograph.py         160 INFO     {"project": "ccle", "project_error_count": 1}
________________________________________________________________________________________________________________________________ test_ensembl ________________________________________________________________________________________________________________________________

protograph = AttrDict({'Cohort': AttrDict({'vertexes': [{'filter': ['hasMember'], 'merge': ...label': 'hasDisease', 'to': 'term:{{disease.term}}'}], 'label': 'Biosample'})})

    def test_ensembl(protograph):
        """ assert ensembl data is ok """
        project_error_count = _validate_project(protograph, 'ensembl')
>       assert project_error_count == 0
E       assert 1 == 0

tests/test_protograph.py:207: AssertionError
----------------------------------------------------------------------------------------------------------------------------- Captured log call ------------------------------------------------------------------------------------------------------------------------------
__init__.py                 54 DEBUG    loading paths from /tmp/SWIFT/biostream/protograph/ensembl
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/ensembl/ensembl.Exon.Edge.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/ensembl/ensembl.Exon.Vertex.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/ensembl/ensembl.Gene.Vertex.json
__init__.py                 45 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/ensembl/ensembl.Gene.Vertex.json", "error_type": "IOError", "error": ""}
__init__.py                 46 ERROR    [Errno 5] Input/output error: '/tmp/SWIFT/biostream/protograph/ensembl/ensembl.Gene.Vertex.json'
Traceback (most recent call last):
  File "/Users/walsbr/ratify/tests/__init__.py", line 33, in _logging
    yield
  File "/Users/walsbr/ratify/tests/test_protograph.py", line 156, in _validate_project
    error_count = _validate_vertex_file(protograph, p)
  File "/Users/walsbr/ratify/tests/test_protograph.py", line 123, in _validate_vertex_file
    for vertex in _load_records(path):
  File "/Users/walsbr/ratify/tests/__init__.py", line 96, in _load_records
    with open(path, 'r') as ins:
IOError: [Errno 5] Input/output error: '/tmp/SWIFT/biostream/protograph/ensembl/ensembl.Gene.Vertex.json'
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/ensembl/ensembl.Transcript.Edge.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/ensembl/ensembl.Transcript.Vertex.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/ensembl/ensembl.Gene.Edge.json
test_protograph.py         160 INFO     {"project": "ensembl", "project_error_count": 1}
_________________________________________________________________________________________________________________________________ test_tcga __________________________________________________________________________________________________________________________________

protograph = AttrDict({'Cohort': AttrDict({'vertexes': [{'filter': ['hasMember'], 'merge': ...label': 'hasDisease', 'to': 'term:{{disease.term}}'}], 'label': 'Biosample'})})

    def test_tcga(protograph):
        """ assert go data is ok """
        for dir_name in _get_dirs('tcga'):
            project_error_count = _validate_project(protograph,
                                                    'tcga/{}'.format(dir_name))
>           assert project_error_count == 0
E           assert 2 == 0

tests/test_protograph.py:227: AssertionError
----------------------------------------------------------------------------------------------------------------------------- Captured log call ------------------------------------------------------------------------------------------------------------------------------
__init__.py                 61 DEBUG    loading paths from /tmp/SWIFT/biostream/protograph/tcga
__init__.py                 54 DEBUG    loading paths from /tmp/SWIFT/biostream/protograph/tcga/TCGA-BRCA
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-BRCA/tcga.TCGA-BRCA.Biosample.Edge.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-BRCA/tcga.TCGA-BRCA.Biosample.Vertex.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-BRCA/tcga.TCGA-BRCA.CNACallSet.Edge.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-BRCA/tcga.TCGA-BRCA.CNACallSet.Vertex.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-BRCA/tcga.TCGA-BRCA.CNASegment.Edge.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-BRCA/tcga.TCGA-BRCA.CNASegment.Vertex.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-BRCA/tcga.TCGA-BRCA.ClinicalFollowup.Edge.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-BRCA/tcga.TCGA-BRCA.ClinicalFollowup.Vertex.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-BRCA/tcga.TCGA-BRCA.DrugTherapy.Edge.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-BRCA/tcga.TCGA-BRCA.GeneExpression.Edge.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-BRCA/tcga.TCGA-BRCA.GeneExpression.Vertex.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-BRCA/tcga.TCGA-BRCA.Individual.Vertex.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-BRCA/tcga.TCGA-BRCA.RadiationTherapy.Edge.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-BRCA/tcga.TCGA-BRCA.RadiationTherapy.Vertex.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-BRCA/tcga.TCGA-BRCA.Individual.Edge.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-BRCA/tcga.TCGA-BRCA.DrugTherapy.Vertex.json
test_protograph.py         160 INFO     {"project": "tcga.TCGA-BRCA", "project_error_count": 0}
__init__.py                 54 DEBUG    loading paths from /tmp/SWIFT/biostream/protograph/tcga/TCGA-LUAD
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-LUAD/tcga.TCGA-LUAD.Biosample.Edge.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-LUAD/tcga.TCGA-LUAD.Biosample.Vertex.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-LUAD/tcga.TCGA-LUAD.CNACallSet.Edge.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-LUAD/tcga.TCGA-LUAD.CNACallSet.Vertex.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-LUAD/tcga.TCGA-LUAD.CNASegment.Edge.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-LUAD/tcga.TCGA-LUAD.CNASegment.Vertex.json
__init__.py                 45 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/tcga/TCGA-LUAD/tcga.TCGA-LUAD.CNASegment.Vertex.json", "error_type": "ValueError", "error": "Extra data: line 1 column 4 - line 2 column 1 (char 3 - 202)"}
__init__.py                 46 ERROR    Extra data: line 1 column 4 - line 2 column 1 (char 3 - 202)
Traceback (most recent call last):
  File "/Users/walsbr/ratify/tests/__init__.py", line 33, in _logging
    yield
  File "/Users/walsbr/ratify/tests/test_protograph.py", line 156, in _validate_project
    error_count = _validate_vertex_file(protograph, p)
  File "/Users/walsbr/ratify/tests/test_protograph.py", line 123, in _validate_vertex_file
    for vertex in _load_records(path):
  File "/Users/walsbr/ratify/tests/__init__.py", line 102, in _load_records
    yield AttrDict(json.loads(line))
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 4 - line 2 column 1 (char 3 - 202)
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-LUAD/tcga.TCGA-LUAD.ClinicalFollowup.Edge.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-LUAD/tcga.TCGA-LUAD.ClinicalFollowup.Vertex.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-LUAD/tcga.TCGA-LUAD.DrugTherapy.Edge.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-LUAD/tcga.TCGA-LUAD.GeneExpression.Edge.json
__init__.py                 45 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/tcga/TCGA-LUAD/tcga.TCGA-LUAD.GeneExpression.Edge.json", "error_type": "IOError", "error": ""}
__init__.py                 46 ERROR    [Errno 5] Input/output error: '/tmp/SWIFT/biostream/protograph/tcga/TCGA-LUAD/tcga.TCGA-LUAD.GeneExpression.Edge.json'
Traceback (most recent call last):
  File "/Users/walsbr/ratify/tests/__init__.py", line 33, in _logging
    yield
  File "/Users/walsbr/ratify/tests/test_protograph.py", line 154, in _validate_project
    error_count = _validate_edge_file(protograph, p)
  File "/Users/walsbr/ratify/tests/test_protograph.py", line 91, in _validate_edge_file
    for edge in _load_records(path):
  File "/Users/walsbr/ratify/tests/__init__.py", line 96, in _load_records
    with open(path, 'r') as ins:
IOError: [Errno 5] Input/output error: '/tmp/SWIFT/biostream/protograph/tcga/TCGA-LUAD/tcga.TCGA-LUAD.GeneExpression.Edge.json'
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-LUAD/tcga.TCGA-LUAD.GeneExpression.Vertex.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-LUAD/tcga.TCGA-LUAD.Individual.Vertex.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-LUAD/tcga.TCGA-LUAD.RadiationTherapy.Edge.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-LUAD/tcga.TCGA-LUAD.RadiationTherapy.Vertex.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-LUAD/tcga.TCGA-LUAD.DrugTherapy.Vertex.json
test_protograph.py          58 DEBUG    /tmp/SWIFT/biostream/protograph/tcga/TCGA-LUAD/tcga.TCGA-LUAD.Individual.Edge.json
test_protograph.py         160 INFO     {"project": "tcga.TCGA-LUAD", "project_error_count": 2}
===================================================================================================================== 3 failed, 6 passed in 7.35 seconds =====================================================================================================================
```

**Comment by prismofeverything** [comment]
Awesome, thanks for this! One last tweak on the ccle samples and we are ready for import.

**Comment by kellrott** [comment]
Can we get an update on the ratify report?

**Comment by bwalsh** [comment]
### biostream

```
docker run -it --rm -v /tmp/SWIFT:/SWIFT -e DATA_DIR=/SWIFT -e SAMPLE_SIZE=10  ratify  pytest  tests/test_biostream.py  |  cut -c 1-256

ERROR:tests:{"path": "/tmp/SWIFT/biostream/biostream/mc3/mc3.VariantAnnotation.json", "error_type": "ValueError", "error": "pb parse e:Failed to load JSON: No JSON object could be decoded. cls:VariantAnnotation path:/tmp/SWIFT/biostream/biostream/mc3/mc3.V
ERROR:tests:pb parse e:Failed to load JSON: No JSON object could be decoded. cls:VariantAnnotation path:/tmp/SWIFT/biostream/biostream/mc3/mc3.VariantAnnotation.json line:ranscriptEffects": [{"featureId": "ENSG00000214842", "effects": [{"term": "SNP"}], "a

```

### protograph 

```
docker run -it --rm -v /tmp/SWIFT:/SWIFT -e DATA_DIR=/SWIFT -e SAMPLE_SIZE=10  ratify  pytest  tests/test_biostream.py  |  cut -c 1-256

__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/ccle/ccle.VariantAnnotation.Edge.json", "error_type": "AssertionError", "error": "incomplete: /tmp/SWIFT/biostream/protograph/ccle/ccle.VariantAnnotation.Edge.json does not c
__init__.py                 49 ERROR    incomplete: /tmp/SWIFT/biostream/protograph/ccle/ccle.VariantAnnotation.Edge.json does not contain keys set(['fromLabel', 'from', 'toLabel', 'label', 'to', 'gid'])
__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/ccle/ccle.CallSet.Edge.json", "error_type": "AssertionError", "error": "incomplete: /tmp/SWIFT/biostream/protograph/ccle/ccle.CallSet.Edge.json does not contain keys set(['fr
__init__.py                 49 ERROR    incomplete: /tmp/SWIFT/biostream/protograph/ccle/ccle.CallSet.Edge.json does not contain keys set(['fromLabel', 'from', 'toLabel', 'label', 'to', 'gid'])
__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/ccle/ccle.GeneExpression.Edge.json", "error_type": "AssertionError", "error": "incomplete: /tmp/SWIFT/biostream/protograph/ccle/ccle.GeneExpression.Edge.json does not contain
__init__.py                 49 ERROR    incomplete: /tmp/SWIFT/biostream/protograph/ccle/ccle.GeneExpression.Edge.json does not contain keys set(['fromLabel', 'from', 'toLabel', 'label', 'to', 'gid'])
__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/ccle/ccle.ResponseCurve.Edge.json", "error_type": "AssertionError", "error": "incomplete: /tmp/SWIFT/biostream/protograph/ccle/ccle.ResponseCurve.Edge.json does not contain k
__init__.py                 49 ERROR    incomplete: /tmp/SWIFT/biostream/protograph/ccle/ccle.ResponseCurve.Edge.json does not contain keys set(['fromLabel', 'from', 'toLabel', 'label', 'to', 'gid'])
__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/ccle/ccle.Variant.Edge.json", "error_type": "AssertionError", "error": "incomplete: /tmp/SWIFT/biostream/protograph/ccle/ccle.Variant.Edge.json does not contain keys set(['fr
__init__.py                 49 ERROR    incomplete: /tmp/SWIFT/biostream/protograph/ccle/ccle.Variant.Edge.json does not contain keys set(['fromLabel', 'from', 'toLabel', 'label', 'to', 'gid'])
__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/ccle/ccle.VariantAnnotation.Edge.json", "error_type": "AssertionError", "error": "incomplete: /tmp/SWIFT/biostream/protograph/ccle/ccle.VariantAnnotation.Edge.json does not c
__init__.py                 49 ERROR    incomplete: /tmp/SWIFT/biostream/protograph/ccle/ccle.VariantAnnotation.Edge.json does not contain keys set(['fromLabel', 'from', 'toLabel', 'label', 'to', 'gid'])
__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/ccle/ccle.GeneExpression.Edge.json", "error_type": "AssertionError", "error": "incomplete: /tmp/SWIFT/biostream/protograph/ccle/ccle.GeneExpression.Edge.json does not contain
__init__.py                 49 ERROR    incomplete: /tmp/SWIFT/biostream/protograph/ccle/ccle.GeneExpression.Edge.json does not contain keys set(['fromLabel', 'from', 'toLabel', 'label', 'to', 'gid'])
__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/ctdd/ctdd.ResponseCurve.Vertex.json", "error_type": "AssertionError", "error": "gid contains blanks 'responseCurve:ccle:CAS1_CENTRAL_NERVOUS_SYSTEM:' in /tmp/SWIFT/biostream/
__init__.py                 49 ERROR    gid contains blanks 'responseCurve:ccle:CAS1_CENTRAL_NERVOUS_SYSTEM:' in /tmp/SWIFT/biostream/protograph/ctdd/ctdd.ResponseCurve.Vertex.json
__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/ctdd/ctdd.Compound.Edge.json", "error_type": "AssertionError", "error": "incomplete: /tmp/SWIFT/biostream/protograph/ctdd/ctdd.Compound.Edge.json does not contain keys set(['
__init__.py                 49 ERROR    incomplete: /tmp/SWIFT/biostream/protograph/ctdd/ctdd.Compound.Edge.json does not contain keys set(['fromLabel', 'from', 'toLabel', 'label', 'to', 'gid'])
__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/ctdd/ctdd.ResponseCurve.Edge.json", "error_type": "AssertionError", "error": "incomplete: /tmp/SWIFT/biostream/protograph/ctdd/ctdd.ResponseCurve.Edge.json does not contain k
__init__.py                 49 ERROR    incomplete: /tmp/SWIFT/biostream/protograph/ctdd/ctdd.ResponseCurve.Edge.json does not contain keys set(['fromLabel', 'from', 'toLabel', 'label', 'to', 'gid'])
__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/ensembl/ensembl.Transcript.Edge.json", "error_type": "AssertionError", "error": "incomplete: /tmp/SWIFT/biostream/protograph/ensembl/ensembl.Transcript.Edge.json does not con
__init__.py                 49 ERROR    incomplete: /tmp/SWIFT/biostream/protograph/ensembl/ensembl.Transcript.Edge.json does not contain keys set(['fromLabel', 'from', 'toLabel', 'label', 'to', 'gid'])
__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/ensembl/ensembl.Exon.Edge.json", "error_type": "AssertionError", "error": "incomplete: /tmp/SWIFT/biostream/protograph/ensembl/ensembl.Exon.Edge.json does not contain keys se
__init__.py                 49 ERROR    incomplete: /tmp/SWIFT/biostream/protograph/ensembl/ensembl.Exon.Edge.json does not contain keys set(['fromLabel', 'from', 'toLabel', 'label', 'to', 'gid'])
__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/go/go.GeneOntologyAnnotation.Edge.json", "error_type": "AssertionError", "error": "incomplete: /tmp/SWIFT/biostream/protograph/go/go.GeneOntologyAnnotation.Edge.json does not
__init__.py                 49 ERROR    incomplete: /tmp/SWIFT/biostream/protograph/go/go.GeneOntologyAnnotation.Edge.json does not contain keys set(['fromLabel', 'from', 'toLabel', 'label', 'to', 'gid'])
__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/go/go.GeneOntologyTerm.Edge.json", "error_type": "AssertionError", "error": "incomplete: /tmp/SWIFT/biostream/protograph/go/go.GeneOntologyTerm.Edge.json does not contain key
__init__.py                 49 ERROR    incomplete: /tmp/SWIFT/biostream/protograph/go/go.GeneOntologyTerm.Edge.json does not contain keys set(['fromLabel', 'from', 'toLabel', 'label', 'to', 'gid'])
__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/mc3/mc3.Variant.Edge.json", "error_type": "AssertionError", "error": "incomplete: /tmp/SWIFT/biostream/protograph/mc3/mc3.Variant.Edge.json does not contain keys set(['fromLa
__init__.py                 49 ERROR    incomplete: /tmp/SWIFT/biostream/protograph/mc3/mc3.Variant.Edge.json does not contain keys set(['fromLabel', 'from', 'toLabel', 'label', 'to', 'gid'])
__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/mc3/mc3.Variant.Vertex.json", "error_type": "ValueError", "error": "No JSON object could be decoded"}
__init__.py                 49 ERROR    No JSON object could be decoded
__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/mc3/mc3.VariantAnnotation.Edge.json", "error_type": "AssertionError", "error": "incomplete: /tmp/SWIFT/biostream/protograph/mc3/mc3.VariantAnnotation.Edge.json does not conta
__init__.py                 49 ERROR    incomplete: /tmp/SWIFT/biostream/protograph/mc3/mc3.VariantAnnotation.Edge.json does not contain keys set(['fromLabel', 'from', 'toLabel', 'label', 'to', 'gid'])
__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/mc3/mc3.CallSet.Edge.json", "error_type": "AssertionError", "error": "incomplete: /tmp/SWIFT/biostream/protograph/mc3/mc3.CallSet.Edge.json does not contain keys set(['fromLa
__init__.py                 49 ERROR    incomplete: /tmp/SWIFT/biostream/protograph/mc3/mc3.CallSet.Edge.json does not contain keys set(['fromLabel', 'from', 'toLabel', 'label', 'to', 'gid'])
__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/tcga/TCGA-SKCM/tcga.TCGA-SKCM.Biosample.Edge.json", "error_type": "AssertionError", "error": "incomplete: /tmp/SWIFT/biostream/protograph/tcga/TCGA-SKCM/tcga.TCGA-SKCM.Biosam
__init__.py                 49 ERROR    incomplete: /tmp/SWIFT/biostream/protograph/tcga/TCGA-SKCM/tcga.TCGA-SKCM.Biosample.Edge.json does not contain keys set(['fromLabel', 'from', 'toLabel', 'label', 'to', 'gid'])
__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/tcga/TCGA-SKCM/tcga.TCGA-SKCM.CNACallSet.Edge.json", "error_type": "AssertionError", "error": "incomplete: /tmp/SWIFT/biostream/protograph/tcga/TCGA-SKCM/tcga.TCGA-SKCM.CNACa
__init__.py                 49 ERROR    incomplete: /tmp/SWIFT/biostream/protograph/tcga/TCGA-SKCM/tcga.TCGA-SKCM.CNACallSet.Edge.json does not contain keys set(['fromLabel', 'from', 'toLabel', 'label', 'to', 'gid'])
__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/tcga/TCGA-SKCM/tcga.TCGA-SKCM.CNASegment.Edge.json", "error_type": "AssertionError", "error": "incomplete: /tmp/SWIFT/biostream/protograph/tcga/TCGA-SKCM/tcga.TCGA-SKCM.CNASe
__init__.py                 49 ERROR    incomplete: /tmp/SWIFT/biostream/protograph/tcga/TCGA-SKCM/tcga.TCGA-SKCM.CNASegment.Edge.json does not contain keys set(['fromLabel', 'from', 'toLabel', 'label', 'to', 'gid'])
__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/tcga/TCGA-SKCM/tcga.TCGA-SKCM.ClinicalFollowup.Edge.json", "error_type": "AssertionError", "error": "incomplete: /tmp/SWIFT/biostream/protograph/tcga/TCGA-SKCM/tcga.TCGA-SKCM
__init__.py                 49 ERROR    incomplete: /tmp/SWIFT/biostream/protograph/tcga/TCGA-SKCM/tcga.TCGA-SKCM.ClinicalFollowup.Edge.json does not contain keys set(['fromLabel', 'from', 'toLabel', 'label', 'to', 'gid'])
__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/tcga/TCGA-SKCM/tcga.TCGA-SKCM.DrugTherapy.Edge.json", "error_type": "AssertionError", "error": "incomplete: /tmp/SWIFT/biostream/protograph/tcga/TCGA-SKCM/tcga.TCGA-SKCM.Drug
__init__.py                 49 ERROR    incomplete: /tmp/SWIFT/biostream/protograph/tcga/TCGA-SKCM/tcga.TCGA-SKCM.DrugTherapy.Edge.json does not contain keys set(['fromLabel', 'from', 'toLabel', 'label', 'to', 'gid'])
__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/tcga/TCGA-SKCM/tcga.TCGA-SKCM.GeneExpression.Edge.json", "error_type": "AssertionError", "error": "incomplete: /tmp/SWIFT/biostream/protograph/tcga/TCGA-SKCM/tcga.TCGA-SKCM.G
__init__.py                 49 ERROR    incomplete: /tmp/SWIFT/biostream/protograph/tcga/TCGA-SKCM/tcga.TCGA-SKCM.GeneExpression.Edge.json does not contain keys set(['fromLabel', 'from', 'toLabel', 'label', 'to', 'gid'])
__init__.py                 48 ERROR    {"path": "/tmp/SWIFT/biostream/protograph/tcga/TCGA-SKCM/tcga.TCGA-SKCM.RadiationTherapy.Edge.json", "error_type": "AssertionError", "error": "incomplete: /tmp/SWIFT/biostream/protograph/tcga/TCGA-SKCM/tcga.TCGA-SKCM
__init__.py                 49 ERROR    incomplete: /tmp/SWIFT/biostream/protograph/tcga/TCGA-SKCM/tcga.TCGA-SKCM.RadiationTherapy.Edge.json does not contain keys set(['fromLabel', 'from', 'toLabel', 'label', 'to', 'gid'])
```

**Comment by buchanae** [comment]
@bwalsh Should we close this?
